---

services:
  postgres:
    image: postgres:latest
    container_name: feature_switch_pg
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: feature_switch_db
    ports:
      - "54329:5432"
    volumes:
      - feature_switch_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: feature_switch_redis
    restart: always
    ports:
      - 63792:6379


volumes:
  feature_switch_postgres_data:
